#!/usr/bin/env ruby
# metaprogramming_demos.rb — all key techniques in one file

puts "=== 1. Open Classes ==="
class Integer
  def factorial
    return 1 if self <= 1
    self * (self - 1).factorial
  end
end

puts 5.factorial   # => 120
puts 10.factorial  # => 3628800


puts "\n=== 2. define_method ==="
class Status
  STATES = %i[draft published archived]

  STATES.each do |state|
    define_method("#{state}!")  { @state = state }
    define_method("#{state}?")  { @state == state }
    define_method("to_s")       { @state.to_s }
  end
end

s = Status.new
s.draft!
puts s.draft?      # => true
puts s.published?  # => false
s.published!
puts s.published?  # => true


puts "\n=== 3. method_missing ==="
class FlexHash
  def initialize;  @data = {};  end

  def method_missing(name, *args)
    if name.to_s.end_with?("=")
      @data[name.to_s.chomp("=").to_sym] = args.first
    else
      @data[name]
    end
  end

  def respond_to_missing?(name, include_private = false)
    true
  end
end

h = FlexHash.new
h.name  = "Yosia"
h.age   = 30
h.city  = "Amsterdam"
puts h.name  # => Yosia
puts h.age   # => 30


puts "\n=== 4. instance_eval DSL ==="
class HtmlBuilder
  def initialize
    @parts = []
  end

  def method_missing(tag, content = nil, &block)
    if block
      inner = HtmlBuilder.new.tap { |b| b.instance_eval(&block) }.to_s
      @parts << "<#{tag}>#{inner}</#{tag}>"
    else
      @parts << "<#{tag}>#{content}</#{tag}>"
    end
  end

  def to_s
    @parts.join("\n")
  end
end

html = HtmlBuilder.new
html.instance_eval do
  div do
    h1 "Hello, Ruby!"
    p  "This HTML was generated by metaprogramming."
  end
end

puts html.to_s


puts "\n=== 5. class_eval to extend at runtime ==="
class Animal
  attr_reader :name
  def initialize(name); @name = name; end
end

["fly", "swim", "run"].each do |action|
  Animal.class_eval do
    define_method("can_#{action}!") do
      @abilities ||= []
      @abilities << action
      self
    end

    define_method("can_#{action}?") do
      (@abilities || []).include?(action)
    end
  end
end

duck = Animal.new("Donald")
duck.can_fly!.can_swim!
puts duck.can_fly?   # => true
puts duck.can_run?   # => false


puts "\n=== 6. inherited hook — plugin registry ==="
class Plugin
  @registry = []

  def self.inherited(subclass)
    @registry << subclass
  end

  def self.all; @registry; end
end

class LogPlugin     < Plugin; def run; puts "Logging...";     end; end
class CachePlugin   < Plugin; def run; puts "Caching...";     end; end
class MetricsPlugin < Plugin; def run; puts "Metrics...";     end; end

puts "Registered plugins:"
Plugin.all.each { |p| p.new.run }


puts "\n=== 7. Build attr_accessor from scratch ==="
module MyAttributes
  def my_attr_accessor(*names)
    names.each do |name|
      define_method(name)       { instance_variable_get("@#{name}") }
      define_method("#{name}=") { |v| instance_variable_set("@#{name}", v) }
    end
  end
end

Class.include(MyAttributes)

class Point
  my_attr_accessor :x, :y

  def initialize(x, y)
    @x, @y = x, y
  end

  def to_s; "(#{x}, #{y})"; end
end

p = Point.new(3, 4)
puts p           # => (3, 4)
p.x = 10
puts p           # => (10, 4)
